name: Gauge and Selenium collaboration in golang
env:
  GOPATH: /home/nirmal/go/src

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Setup:
    name: job for initial setup.
    runs-on: self-hosted
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Copy workspace inside GOPATH
      run: |
        mkdir ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}
        cp -r . ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}/
        
    - name: gauge install xml-report
      shell: sh
      run: |
        cd ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}/
        gauge install xml-report
        
  Run-Test:
    needs: [Setup]
    name: Job for Running tests
    runs-on: self-hosted
    
    steps:
      - name: Runing Gauge Test
        shell: sh
        run: |
          echo "gopath is $GOPATH"
          cd ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}
          gauge run specs
        
      - name: Copy xml report to github workspace
        shell: sh
        run: |
          cp ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}/reports/xml-report/result.xml result.xml
        
      - name: Publishing report
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: result.xml
