name: Gauge and Selenium collaboration in golang
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  
  Setup:
    name: job for initial setup.
    runs-on: self-hosted
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Copy workspace inside GOPATH
      shell: sh
      run: |
        if [ -d $GOPATH/src/github.com/${{ github.event.repository.name }} ];
        then
          echo "Directory present"
        else
          echo "Directory Not present" 
          mkdir $GOPATH/src/github.com/${{ github.event.repository.name }}
        fi
        cp -r . $GOPATH/src/github.com/${{ github.event.repository.name }}/
        
    - name: gauge install xml-report
      shell: sh
      run: |
        cd $GOPATH/src/github.com/${{ github.event.repository.name }}/
        gauge install xml-report
        
  Test:
    if: always()
    needs: [Setup]
    name: Job for Running tests
    runs-on: self-hosted
    
    steps:
      - name: Runing Gauge Test
        shell: sh
        run: |
          echo "gopath is $GOPATH"
          cd $GOPATH/src/github.com/${{ github.event.repository.name }}
          gauge run specs
        
      - name: Copy xml report to github workspace
        shell: sh
        run: |
          cp $GOPATH/src/github.com/${{ github.event.repository.name }}/reports/xml-report/result.xml result.xml
  Publish-Test-Report:
    if: always()
    name: Publish Test report
    needs: Test
    runs-on: self-hosted
    steps:
      - name: Publishing report
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: result.xml
