name: Gauge and Selenium collaboration in golang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: self-hosted
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Copy workspace inside GOPATH
      run: |
        mkdir /home/nirmal/go/src/github.com/gauge-selenium-go
        cp -r . /home/nirmal/go/src/github.com/gauge-selenium-go/
    - name: gauge install xml-report
      run: |
        cd /home/nirmal/go/src/github.com/gauge-selenium-go/
        gauge install xml-report
    - name: Runing Gauge Test
      run: |
        cd /home/nirmal/go/src/github.com/gauge-selenium-go/
        gauge run specs/
    - name: Print present working directory
      shell: sh
      run: |
        echo -e "\n PWD: \n"
        pwd
    - name: Publishing report
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: /home/nirmal/go/src/github.com/gauge-selenium-go/reports/xml-report/result.xml
