name: Gauge and Selenium collaboration in golang
env:
  GOPATH: /home/nirmal/go/src/

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: self-hosted
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Copy workspace inside GOPATH
      run: |
        mkdir ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}
        cp -r . ${{ env.GOPATH }}/github.com/${{ github.event.repository.name }}
